spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://218.145.165.138:3306/xeTestDb
    username: xehub
    password: xef!@#123

mybatis:
  type-aliases-package: com.xe.api.application.**.dto,
  type-handlers-package: com.xe.api.application.**.dto
  mapper-locations: sqlmap/*_SQL.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL

server:
  port: 8081